### PR TITLE
Fixing is_clang wrongly returning false on macOS

### PR DESCRIPTION
**Pull request by bryantdrewjones**
is_clang returns ‘false’ if cc() returns a full path to the clang executable (e.g., CC=$(xcrun --find clang), causing the driver function cc() to return “/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang”).

This fix does the same comparison as before, but on the token at the end of the full path.

### CODE REVIEW

**Comment by SanderMertens** [comment]
Ah, could you modify the PR so that it uses `strrchr`? That way you don't need the loop / malloc. Works like this:

```c
char *ptr = strrchr(cc, UT_OS_PS); // ptr now points to the last occurrence of / or \
```

**Comment by bryantdrewjones** [comment]
Ooh, yes, that's great! I pushed an update 🙂 Thanks for checking, @SanderMertens!

**Comment by SanderMertens** [comment]
I just merged your change with master (not sure why it's not showing up here). I tweaked it a little bit so that your fix can be used for all compilers. Thanks again!

(and sorry again for being so late- not sure if "late" even covers it anymore :p)

**Comment by SanderMertens** [comment]
For ref, this is what the code looks like now: https://github.com/SanderMertens/bake/blob/master/drivers/lang/c/src/gcc/driver.c#L73

**Pull request closed without merging**
